-- M10 (theme builder): the launch theme gains header, footer, product and collection pages, and its
-- tokens move to the editable shape (colours, fonts, corners, buttons). Data-only and idempotent.
-- JSON mirrors packages/domain/src/themes/launch-template.ts (a test keeps them in sync).
-- Stores that already activated this theme keep their own copy; they see "update available".
UPDATE "theme_templates"
SET
  "default_pages" = "default_pages" || '{"collection":[{"id":"ec-collection","type":"CollectionListing","version":1,"props":{"columns":"4","showFilters":true,"showDescription":true}},{"id":"ec-collection-cta","type":"CallToAction","version":1,"props":{"heading":"Can''t find what you need?","text":"Message us and we''ll help you choose.","primaryLabel":"Contact us","primaryHref":"/pages/contact","overlayOpacity":45,"tone":"primary","align":"center"}}],"product":[{"id":"ec-product","type":"ProductDetail","version":1,"props":{"galleryPosition":"left","showBreadcrumb":true,"showRating":true,"showDescription":true,"showTags":true}},{"id":"ec-product-usp","type":"UspStrip","version":1,"props":{"items":[{"icon":"Truck","title":"Free shipping","description":"On orders above ₹999"},{"icon":"ShieldCheck","title":"Secure checkout","description":"UPI, cards and cash on delivery"},{"icon":"RotateCcw","title":"Easy returns","description":"7-day return guarantee"}]}},{"id":"ec-product-more","type":"ProductCarousel","version":1,"props":{"title":"You may also like","source":"newest","limit":8,"columns":"4","showPrice":true,"showRating":false,"tone":"default"}}],"header":[{"id":"ec-header","type":"SiteHeader","version":1,"props":{"links":[{"label":"Home","href":"/"},{"label":"Shop","href":"/collections/all"},{"label":"Our story","href":"/pages/about"}],"layout":"left","showSearch":true,"showCart":true,"sticky":true,"tone":"default"}}],"footer":[{"id":"ec-footer","type":"SiteFooter","version":1,"props":{"about":"Small-batch products from makers you can trust, delivered across India.","columns":[{"title":"Shop","links":[{"label":"All products","href":"/collections/all"},{"label":"Search","href":"/search"}]},{"title":"Policies","links":[{"label":"Privacy Policy","href":"/policies/privacy"},{"label":"Terms of Service","href":"/policies/terms"},{"label":"Refund Policy","href":"/policies/refund"},{"label":"Shipping Policy","href":"/policies/shipping"}]}],"showNewsletter":true,"newsletterTitle":"Newsletter","newsletterText":"Subscribe for updates and exclusive offers.","tone":"surface"}}]}'::jsonb,
  "draft_pages" = COALESCE("draft_pages", "default_pages") || '{"collection":[{"id":"ec-collection","type":"CollectionListing","version":1,"props":{"columns":"4","showFilters":true,"showDescription":true}},{"id":"ec-collection-cta","type":"CallToAction","version":1,"props":{"heading":"Can''t find what you need?","text":"Message us and we''ll help you choose.","primaryLabel":"Contact us","primaryHref":"/pages/contact","overlayOpacity":45,"tone":"primary","align":"center"}}],"product":[{"id":"ec-product","type":"ProductDetail","version":1,"props":{"galleryPosition":"left","showBreadcrumb":true,"showRating":true,"showDescription":true,"showTags":true}},{"id":"ec-product-usp","type":"UspStrip","version":1,"props":{"items":[{"icon":"Truck","title":"Free shipping","description":"On orders above ₹999"},{"icon":"ShieldCheck","title":"Secure checkout","description":"UPI, cards and cash on delivery"},{"icon":"RotateCcw","title":"Easy returns","description":"7-day return guarantee"}]}},{"id":"ec-product-more","type":"ProductCarousel","version":1,"props":{"title":"You may also like","source":"newest","limit":8,"columns":"4","showPrice":true,"showRating":false,"tone":"default"}}],"header":[{"id":"ec-header","type":"SiteHeader","version":1,"props":{"links":[{"label":"Home","href":"/"},{"label":"Shop","href":"/collections/all"},{"label":"Our story","href":"/pages/about"}],"layout":"left","showSearch":true,"showCart":true,"sticky":true,"tone":"default"}}],"footer":[{"id":"ec-footer","type":"SiteFooter","version":1,"props":{"about":"Small-batch products from makers you can trust, delivered across India.","columns":[{"title":"Shop","links":[{"label":"All products","href":"/collections/all"},{"label":"Search","href":"/search"}]},{"title":"Policies","links":[{"label":"Privacy Policy","href":"/policies/privacy"},{"label":"Terms of Service","href":"/policies/terms"},{"label":"Refund Policy","href":"/policies/refund"},{"label":"Shipping Policy","href":"/policies/shipping"}]}],"showNewsletter":true,"newsletterTitle":"Newsletter","newsletterText":"Subscribe for updates and exclusive offers.","tone":"surface"}}]}'::jsonb,
  "default_tokens" = '{"colors":{"primary":"#0b6b42","secondary":"#334155","accent":"#f59e0b","background":"#ffffff","surface":"#f4f7f5","text":"#16201b"},"fonts":{"heading":"Inter","body":"Inter"},"radius":"md","buttons":{"style":"solid","uppercase":false}}'::jsonb,
  "draft_tokens" = '{"colors":{"primary":"#0b6b42","secondary":"#334155","accent":"#f59e0b","background":"#ffffff","surface":"#f4f7f5","text":"#16201b"},"fonts":{"heading":"Inter","body":"Inter"},"radius":"md","buttons":{"style":"solid","uppercase":false}}'::jsonb,
  "features" = '["Hero banner","Product carousel","Testimonials","Call to action","FAQ","Header and footer","Product and collection pages","Mobile-first"]'::jsonb,
  "version" = "version" + 1,
  "updated_at" = now()
WHERE "code" = 'essential-commerce'
  AND NOT ("default_pages" ? 'header');
